# Generated by Django 6.0.5 on 2026-06-01 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='contactmessage',
            table='contact_messages',
        ),
    ]
